### ISSUE TITLE
value does not change

### ISSUE THREAD

**Issue by kazuya86** [MojtabaHs/LabeledStepper#2]
Value does not change in iOS17.4. 
This is just what I simply used in SwiftUI View. Is there any idea to solve?

```
@State private var IP: Int = 0
,,,
    LabeledStepper("Inning", value: $IP, in: 0...10)
```

**Comment by MojtabaHs** [comment]
Let me check and I'll get back to you @kazuya86

**Comment by MojtabaHs** [comment]
I have added a working demo to the preview with configurations like yours and it's working already. Can you please open a PR with a non-working demo so that I can investigate? @kazuya86

**Comment by kazuya86** [comment]
Thank you for reply quickly! It seems that LabeledStepper does not work into Form and List. I also confirmed it's working outside of Form and List. Hope we can utilize it within Form and List as well.

**Comment by MojtabaHs** [comment]
@kazuya86 This is because of the default `Button` behavior of `SwiftUI` in the lists. You should change the `.buttonStyle()` to anything OTHER THAN the `.default` like:

```
LabeledStepper(
    "Title",
     description: "description",
     value: $value,
     in: 0...10
)
.buttonStyle(.plain)
```

**Comment by kazuya86** [comment]
Thank you for investigation. I'm also ok now after adding buttonStyle
